### ISSUE TITLE
UIWebView 의존성 제거 요청

### ISSUE THREAD

**Issue by y2ducky** [nhn/adlib.ios_media_app#1]
앱을 앱스토에 제출하면 다음과 같은 경고 메일이 옵니다.
Adlib 라이브러리에서 Deprecated된 UIWebView 를 사용하고 있다면 WKWebView로 교체 해주시길 부탁드립니다.

"ITMS-90809: Deprecated API Usage - App updates that use UIWebView will no longer be accepted as of December 2020. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview)."

**Comment by didianfrp** [comment]
5.1.2 버전에 UIWebView를 WKWebView로 전환하였습니다.
감사합니다.

**Comment by swtalk** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
박시우(viewrain@nhn.com) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
박시우(viewrain@nhn.com) 
          
          
            * 발송 시간 : 
2020-07-24T11:37:20
          
          
            * 메일 제목 : 
Re: [nhn/adlib.ios_media_app] UIWebView 의존성 제거 요청 (#1)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          dooray@nhn.com
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by swtalk** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
박시우(viewrain@nhn.com) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
박시우(viewrain@nhn.com) 
          
          
            * 발송 시간 : 
2020-08-21T10:43:05
          
          
            * 메일 제목 : 
Re: [nhn/adlib.ios_media_app] UIWebView 의존성 제거 요청 (#1)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          dooray@nhn.com
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.
