### ISSUE TITLE
v5.1.2에서 INVALID_SESSION 문제

### ISSUE THREAD

**Issue by y2ducky** [nhn/adlib.ios_media_app#2]
v5.1.2(296ae75)로 업그레이드 해보고 있습니다. 하지만 다음과 같은 문제가 있습니다.
확인부탁드립니다.

- 특정 Adlib Key으로 설정하면, 아래와 같은 오류가 발생합니다.
  - v5.1.1에서는 정상 동작하는 key 값입니다.
  - 로그상으로, "INVALID_SESSION" 오류가 발생하여 AdNetwork 목록조차 가져오지 못합니다.
- 특정 Adlib Key으로 설정하면, AdNetwork 목록을 정상적으로 가져오고 광고도 보입니다.
  - 이 때도 user-agent 오류는 동일하게 발생합니다.
- 국가별로 다른 Adlib key값을 사용하고 있는데, 폰 설정에서 지역(국가)를 변경한 뒤로 문제가 잘 발행하는 것 같습니다.

추가로, v5.1.2에서는 ADLibSDK()를 실행해주는 것처럼 바뀌었던데 필수인가요?

```
[Adlib] ALAdBannerView state : Optional("STARTED"), info : nil
user_agent : (null)
ADLIB: Failed to initialize User-agent
user_agent : (null)
ADLIB: Failed to initialize User-agent
user_agent : (null)
ADLIB: Failed to initialize User-agent
user_agent : (null)
ADLIB: Failed to initialize User-agent
user_agent : (null)
ADLIB: Failed to initialize User-agent
user_agent : (null)
ADLIB: Failed to initialize User-agent
[Adlib] ALAdBannerView state : Optional("INVALID_SESSION"), info : nil
[Adlib] ALAdBannerView state : Optional("STOPPED"), info : nil
```

**Comment by swtalk** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
박시우(viewrain@nhn.com) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
박시우(viewrain@nhn.com) 
          
          
            * 발송 시간 : 
2020-07-30T09:27:23
          
          
            * 메일 제목 : 
[nhn/adlib.ios_media_app] v5.1.2에서 INVALID_SESSION 문제 (#2)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          dooray@nhn.com
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by y2ducky** [comment]
v5.1.3에서 해결된 것을 확인했습니다.

**Comment by swtalk** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
박시우(viewrain@nhn.com) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
박시우(viewrain@nhn.com) 
          
          
            * 발송 시간 : 
2020-08-21T10:43:05
          
          
            * 메일 제목 : 
Re: [nhn/adlib.ios_media_app] v5.1.2에서 INVALID_SESSION 문제 (#2)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          dooray@nhn.com
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by swtalk** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
박시우(viewrain@nhn.com) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
박시우(viewrain@nhn.com) 
          
          
            * 발송 시간 : 
2020-08-21T10:43:45
          
          
            * 메일 제목 : 
Re: [nhn/adlib.ios_media_app] v5.1.2에서 INVALID_SESSION 문제 (#2)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          dooray@nhn.com
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.
